travis:
  secure:
    BINSTAR_TOKEN: QbBzr5Rc6Q6yqcz9QJPqPeVcCdppOvZ6Lt5iqW5j40KFPgTdJQg5LokwdSpcT2cNc0K3UO1pjckSGO2nm6n2wTkTyDZkbXumPXzj3rnxmPTqWogu9O00mbgT6rbCuSMrdUwv2hx2tyjLW0WuEt59CvbUq8j9GQLiL1MEyyuH3C3KqP7fLEheIVTxG236P6nlz/ZlY/E5SdsOhNMYogbiPhxoDqv8zdY20kx5fd/QC/Wf0MqV4eJBCe9/fdnJBOcVpSQE/hnMu/pq40rI69xblMnxaZX4sKl+6E33HivmXJInOT+yJGOBkzFQe4cB28ui/iiTua7MRcpHVtfiYwh1oatRPSPMOF+xw7dbwdUyI/pz0FFo8Z7P25VTSG1TyHRmlPz7JJAXs+cR9EnXioBnPQ+TvOAc/AZDyrzlcrzNnU1jrlYWXse5H35bJFzpXcEHxbPWw/pfM112pR+vNAdEVwJU1rz01EhMEy61T3vr6v7VdzFDkPmvmxQWgdizyKzi3m+Mo/KDQm2zunDf6QBLbMUnIt1HsygzkOZ+NsDwnE6rrsQH5H0XUFfYmKihXrtWZeCGRbq0Z73ZPh4V9BbpXmBDxINWUVpzGPCv23PtZWq47JXF6K/KQlkTbdnKXfNZIitBPFyaKAEi4xQ+mqduvgoMLjuQwkfvXytlF2a0EPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
